### ISSUE TITLE
IE9 XHR .open Issue

### ISSUE THREAD

**Issue by markmutti** [SOASTA/mpulse.js#19]
<img width="706" alt="screen shot 2016-07-11 at 10 55 53 am" src="https://cloud.githubusercontent.com/assets/5241549/16743279/617b14b6-4760-11e6-83dd-d83f84006d3a.png">
<img width="660" alt="screen shot 2016-07-11 at 10 56 40 am" src="https://cloud.githubusercontent.com/assets/5241549/16743280/617c9f98-4760-11e6-9b0f-998ec41fabde.png">

This is a known issue with IE9 and [has a few workarounds] (http://stackoverflow.com/questions/5793831/script5-access-is-denied-in-ie9-on-xmlhttprequest).

We're forking mpulse.js now and I'll contribute a fix if I get a clean one working.

**Comment by nicjansma** [comment]
Thanks Mark!  To confirm, you see this in IE9 only?  We should fall back to `XDomainRequest` for IE9 (which is where I've heard of this error appearing before)

**Comment by markmutti** [comment]
Yes sir, and thank you for your prompt response! A QA initially found the issue on a machine natively running IE9, and I'm able to reproduce it on [the "IE9 on Win7" VM from Microsoft] (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

<img width="389" alt="screen shot 2016-07-11 at 2 17 48 pm" src="https://cloud.githubusercontent.com/assets/5241549/16747108/5d5f27d4-4772-11e6-8c15-ecd23411e859.png">

**Comment by nicjansma** [comment]
Should be fixed by https://github.com/SOASTA/mpulse.js/issues/20
